application: himopie-gae-python
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /css
  static_dir: css
- url: /javascript
  static_dir: javascript
- url: /lib
  static_dir: lib
- url: /fujiwara/?
  script: handler/fujiwara/fujiwara.py
- url: /.*
  script: handler/index/index.py

libraries:
- name: django
  version: "1.4"

env_variables:
    DJANGO_SETTINGS_MODULE: 'settings'

